import React from 'react'
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff'
  },
  title: {
    fontSize: 24,
    marginBottom: 20
  },
  table: {
    width: '80%',
    marginVertical: 30,
    borderWidth: 1,
    borderColor: '#000000'
  },
  row: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: '#000000',
    height: 30
  },
  cell: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center'
  },
  topLeftCorner: {
    left: 30
  },
  topRightCorner: {
    right: 30
  },
  cornerText: {
    position: 'absolute',
    top: 30,
    fontSize: 12
  }
})

const Report = ({ productsList }) => (
  <Document>
    <Page size='A2' style={styles.page}>
      <Text style={[styles.cornerText, styles.topLeftCorner]}>Phone Shop</Text>
      <Text style={[styles.cornerText, styles.topRightCorner]}>Báo cáo hàng tồn kho</Text>
      <Text style={styles.title}>Product Report</Text>
      <Text style={{ marginBottom: 10 }}>Report generated on: {new Date().toLocaleString()}</Text>
      <Text style={{ marginBottom: 10 }}>Generated by: Nguyen Cong Hiep</Text>
      <View style={styles.table}>
        <View style={styles.row}>
          <View style={[styles.cell, { borderRightWidth: 1 }]}>
            <Text>ID</Text>
          </View>
          <View style={[styles.cell, { borderRightWidth: 1 }]}>
            <Text>Name</Text>
          </View>
          <View style={[styles.cell, { borderRightWidth: 1 }]}>
            <Text>Price</Text>
          </View>
          <View style={styles.cell}>
            <Text>Quantity</Text>
          </View>
          <View style={styles.cell}>
            <Text>Sold</Text>
          </View>
        </View>
        {productsList.map((item, index) => (
          <View key={index} style={styles.row}>
            <View style={[styles.cell, { borderRightWidth: 1 }]}>
              <Text>{item.productsId}</Text>
            </View>
            <View style={[styles.cell, { borderRightWidth: 1 }]}>
              <Text>{item.productsName}</Text>
            </View>
            <View style={[styles.cell, { borderRightWidth: 1 }]}>
              <Text>{item.price}</Text>
            </View>
            <View style={[styles.cell, { borderRightWidth: 1 }]}>
              <Text>{item.quantity}</Text>
            </View>
            <View style={styles.cell}>
              <Text>{item.sold}</Text>
            </View>
          </View>
        ))}
      </View>
      <Text style={styles.footer}>Signature: ____________________</Text>
    </Page>
  </Document>
)

export default Report
